import {useState,type FormEvent} from 'react';
import {doc,runTransaction,serverTimestamp} from 'firebase/firestore';
import type {Allocation} from '../types';
import {db} from '../firebase';
import {formatNaira,parseNaira} from '../money';

export default function BudgetEditor({allocations,total,onClose,ping}:{allocations:Allocation[];total:number;onClose:()=>void;ping:(message:string)=>void}){
  const [rows,setRows]=useState(allocations.map(x=>({id:x.id,category:x.category,amount:String(x.amount)})));
  const [budget,setBudget]=useState(String(total));const [busy,setBusy]=useState(false);
  async function save(e:FormEvent){e.preventDefault();if(!db)return;const firestore=db;setBusy(true);try{const amount=parseNaira(budget);const next=rows.map(x=>({id:x.id,amount:parseNaira(x.amount)}));if(next.reduce((n,x)=>n+x.amount,0)!==amount)throw new Error('Allocations must add up exactly to the total budget.');await runTransaction(firestore,async tx=>{const refs=next.map(x=>doc(firestore,'budgetAllocations',x.id)),snapshots=await Promise.all(refs.map(ref=>tx.get(ref)));if(snapshots.some(s=>!s.exists()))throw new Error('Budget allocation is missing.');next.forEach((x,i)=>tx.update(refs[i],{amount:x.amount,updatedAt:serverTimestamp()}));tx.set(doc(firestore,'budgets','event-2026'),{name:'SLK Rave 2026',totalAmount:amount,year:2026,updatedAt:serverTimestamp()},{merge:true})});ping('Budget updated.');onClose();}catch(e:any){ping(e.message||'Could not update the budget.');}finally{setBusy(false)}}
  return <div className="modal-overlay" onClick={onClose}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><div className="eyebrow">ADMIN CONTROLS</div><h2>Edit event budget</h2></div><button className="icon-button" type="button" onClick={onClose}>×</button></div><form onSubmit={save}><div className="modal-body"><label>Total budget (₦)<input type="number" min="0" step="1" value={budget} onChange={e=>setBudget(e.target.value)} required/></label>{rows.map((row,i)=><label key={row.id}>{row.category}<input type="number" min="0" step="1" value={row.amount} onChange={e=>setRows(old=>old.map((x,j)=>j===i?{...x,amount:e.target.value}:x))} required/></label>)}<div className="callout"><span>Finance users should review paid expenses against category allocations before confirming payment.</span></div><div className="callout"><span>Current allocation total: <b>{formatNaira(rows.reduce((n,x)=>n+(Number(x.amount)||0),0))}</b></span></div></div><div className="modal-foot"><button type="button" className="btn secondary" onClick={onClose}>Cancel</button><button disabled={busy} className="btn primary">{busy?'Saving…':'Save budget'}</button></div></form></div></div>
}
