import {useEffect,useRef,useState,type FormEvent} from 'react';
import {collection,doc,getDoc,onSnapshot,runTransaction,type Firestore,serverTimestamp,writeBatch} from 'firebase/firestore';
import {Plus, X} from 'lucide-react';
import type {Expense,Revenue} from '../types';
import {notifyError} from '../errorHandling';
import {queueWorkspaceAudit} from '../configurationAudit';
import {configurationAuditChanges} from '../configurationChanges.mjs';
import ModalDialog from './ModalDialog';

const defaultRevenue=['Ticket Sales','Bar & Merch Sales','Sponsorships','Vendor Booth Fees','Support / Donations'];
const defaultExpense=['Talent & Booking','Venue & Production','Marketing & Promo','Operations & Safety'];
const colors=['#00F5FF','#FF2BD6','#B6FF00','#7C69FF','#FFB547'];
type Category={id:string;name:string;active:boolean;systemControlled?:boolean;description?:string};
function categoryState(value:Record<string,unknown>|null){if(!value)return null;return Object.fromEntries(['name','active','systemControlled','description'].filter(field=>Object.hasOwn(value,field)).map(field=>[field,value[field]]))}
export default function Categories({revenues,expenses,db,actor,actorId,ping}:{revenues:Revenue[];expenses:Expense[];db:Firestore|null;actor:string;actorId:string;ping:(message:string)=>void}){
  const [rev,setRev]=useState<Category[]>(defaultRevenue.map((name,i)=>({id:`rev-${i}`,name,active:true,systemControlled:name==='Ticket Sales'})));
  const [exp,setExp]=useState<Category[]>(defaultExpense.map((name,i)=>({id:`exp-${i}`,name,active:true})));
  const [name,setName]=useState(''),[kind,setKind]=useState<'revenue'|'expense'>('revenue'),[editing,setEditing]=useState<{id:string;kind:'revenue'|'expense';name:string}|null>(null),[editName,setEditName]=useState(''),[creating,setCreating]=useState(false);
  const pendingCreate=useRef<{kind:'revenue'|'expense';name:string;categoryId:string;auditId:string}|null>(null);
  function optionalReason(){const value=window.prompt('Optional reason for this category change (up to 500 characters):');if(value===null)return '';const reason=value.trim();if(reason.length>500){ping('Reason must be 500 characters or fewer.');return undefined}return reason}
  useEffect(()=>{if(!db)return;const fail=(name:string)=>(error:unknown)=>notifyError(`load ${name}`,error,ping,`${name} could not be loaded. Check your connection and permissions.`);const a=onSnapshot(collection(db,'revenueCategories'),s=>setRev(s.docs.map(d=>({id:d.id,...d.data()} as Category))),fail('Revenue categories'));const b=onSnapshot(collection(db,'expenseCategories'),s=>setExp(s.docs.map(d=>({id:d.id,...d.data()} as Category))),fail('Expense categories'));return()=>{a();b()}},[db]);
  async function create(e:FormEvent){e.preventDefault();const value=name.trim();if(value.length<2||value.length>60){ping('Category names must be 2–60 characters.');return}if(!db){ping('This app is not connected. Refresh the page or contact the administrator.');return}if(creating)return;const reason=optionalReason();if(reason===undefined)return;setCreating(true);let attempt=pendingCreate.current;if(!attempt||attempt.kind!==kind||attempt.name!==value){attempt={kind,name:value,categoryId:doc(collection(db,kind==='revenue'?'revenueCategories':'expenseCategories')).id,auditId:crypto.randomUUID()};pendingCreate.current=attempt}const collectionName=attempt.kind==='revenue'?'revenueCategories':'expenseCategories',ref=doc(db,collectionName,attempt.categoryId);try{if((await getDoc(ref)).exists()){pendingCreate.current=null;if(name.trim()===attempt.name)setName('');ping('Category added.');return}const batch=writeBatch(db),after={name:attempt.name,active:true,systemControlled:false};queueWorkspaceAudit(batch,db,actor,actorId,attempt.auditId,reason||undefined,configurationAuditChanges([{path:`${collectionName}/${attempt.categoryId}`,before:null,after}]));batch.set(ref,{...after,createdAt:serverTimestamp()});await batch.commit();pendingCreate.current=null;if(name.trim()===attempt.name)setName('');ping('Category added.')}catch(error:unknown){notifyError('create category',error,ping,'Could not add the category. Please try again.')}finally{setCreating(false)}}
  async function toggle(c:Category,which:'revenue'|'expense'){if(!db||c.systemControlled)return;const reason=optionalReason();if(reason===undefined)return;const ref=doc(db,which==='revenue'?'revenueCategories':'expenseCategories',c.id),auditId=crypto.randomUUID();try{await runTransaction(db,async transaction=>{const snapshot=await transaction.get(ref);if(!snapshot.exists())throw new Error('Category no longer exists. Refresh and try again.');const data=snapshot.data(),wasActive=data.active!==false,after={...categoryState(data),active:!wasActive},changes=configurationAuditChanges([{path:`${which==='revenue'?'revenueCategories':'expenseCategories'}/${c.id}`,before:categoryState(data),after}]);transaction.update(ref,{active:!wasActive,updatedAt:serverTimestamp()});queueWorkspaceAudit(transaction,db,actor,actorId,auditId,reason||undefined,changes)});ping(c.active?'Category archived.':'Category activated.')}catch(error:unknown){notifyError('update category',error,ping,'Could not update the category. Please try again.')}}
  function beginEdit(c:Category,which:'revenue'|'expense'){if(c.systemControlled)return;setEditing({id:c.id,kind:which,name:c.name});setEditName(c.name)}
  async function saveEdit(e:FormEvent){e.preventDefault();if(!db||!editing)return;const value=editName.trim();if(value.length<2||value.length>60){ping('Category names must be 2–60 characters.');return}const reason=optionalReason();if(reason===undefined)return;const collectionName=editing.kind==='revenue'?'revenueCategories':'expenseCategories',ref=doc(db,collectionName,editing.id),auditId=crypto.randomUUID();try{await runTransaction(db,async transaction=>{const snapshot=await transaction.get(ref);if(!snapshot.exists())throw new Error('Category no longer exists. Refresh and try again.');const data=snapshot.data(),before=categoryState(data),after={...before,name:value};if(data.name===value)return;const changes=configurationAuditChanges([{path:`${collectionName}/${editing.id}`,before,after}]);transaction.update(ref,{name:value,updatedAt:serverTimestamp()});queueWorkspaceAudit(transaction,db,actor,actorId,auditId,reason||undefined,changes)});setEditing(null);ping('Category updated. Historical transaction snapshots are unchanged.')}catch(error:unknown){notifyError('rename category',error,ping,'Could not update the category. Please try again.')}}
  function section(title:string,items:Category[],which:'revenue'|'expense',counts:(c:string)=>number){return <div className="panel"><div className="panel-head"><div><h3>{title}</h3><p>{which==='revenue'?'Organize your event income':'Classify and track event costs'}</p></div><span className="counter">{items.filter(x=>x.active).length} ACTIVE</span></div>{items.map((c,i)=><div className="category-row" key={c.id}><span className="cat-swatch" style={{background:colors[i%colors.length]}}/><div><b>{c.name}</b><small>{c.systemControlled?'System controlled':`${counts(c.name)} transactions`}</small></div><span className={`category-state ${c.active?'':'inactive'}`}><i/>{c.active?'Active':'Archived'}</span>{!c.systemControlled&&<div className="category-actions"><button className="text-action" onClick={()=>beginEdit(c,which)}>Edit</button><button className="text-action" onClick={()=>toggle(c,which)}>{c.active?'Archive':'Activate'}</button></div>}</div>)}</div>}
  return <><div className="category-grid">{section('Revenue categories',rev,'revenue',c=>revenues.filter(x=>x.category===c).length)}{section('Expense categories',exp,'expense',c=>expenses.filter(x=>x.category===c).length)}</div><div className="panel add-category"><div><h3>Add a category</h3><p>New categories appear in future transactions.</p></div><form onSubmit={create}><label htmlFor="new-category-type">Type<select id="new-category-type" value={kind} onChange={e=>setKind(e.target.value as 'revenue'|'expense')}><option value="revenue">Revenue</option><option value="expense">Expense</option></select></label><label htmlFor="new-category-name">Category name<input id="new-category-name" value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Sponsorships"/></label><button className="btn primary"><Plus size={15}/> Add category</button></form></div><div className="callout"><span><b>Historical records stay intact.</b> Renaming stores a new category label for future records. Categories cannot be deleted; archive them instead.</span></div>{editing&&<ModalDialog onClose={()=>setEditing(null)} labelledBy="edit-category-dialog-title"><div className="modal-head"><div><div className="eyebrow">CATEGORY SETTINGS</div><h2 id="edit-category-dialog-title">Edit category</h2></div><button className="icon-button" onClick={()=>setEditing(null)} aria-label="Close"><X/></button></div><form onSubmit={saveEdit}><div className="modal-body"><label>Category name<input value={editName} onChange={e=>setEditName(e.target.value)} required maxLength={60}/></label></div><div className="modal-foot"><button type="button" className="btn secondary" onClick={()=>setEditing(null)}>Cancel</button><button className="btn primary">Save changes</button></div></form></ModalDialog>}</>
}
