import {useEffect,useState,type FormEvent} from 'react';
import {collection,doc,onSnapshot,type Firestore,updateDoc,serverTimestamp,addDoc} from 'firebase/firestore';
import {Plus, X} from 'lucide-react';
import type {Expense,Revenue} from '../types';
import {notifyError} from '../errorHandling';

const defaultRevenue=['Ticket Sales','Bar & Merch Sales','Sponsorships','Vendor Booth Fees','Support / Donations'];
const defaultExpense=['Talent & Booking','Venue & Production','Marketing & Promo','Operations & Safety'];
const colors=['#00F5FF','#FF2BD6','#B6FF00','#7C69FF','#FFB547'];
type Category={id:string;name:string;active:boolean;systemControlled?:boolean;description?:string};
export default function Categories({revenues,expenses,db,ping}:{revenues:Revenue[];expenses:Expense[];db:Firestore|null;ping:(message:string)=>void}){
  const [rev,setRev]=useState<Category[]>(defaultRevenue.map((name,i)=>({id:`rev-${i}`,name,active:true,systemControlled:name==='Ticket Sales'})));
  const [exp,setExp]=useState<Category[]>(defaultExpense.map((name,i)=>({id:`exp-${i}`,name,active:true})));
  const [name,setName]=useState(''),[kind,setKind]=useState<'revenue'|'expense'>('revenue'),[editing,setEditing]=useState<{id:string;kind:'revenue'|'expense';name:string}|null>(null),[editName,setEditName]=useState('');
  useEffect(()=>{if(!db)return;const fail=(name:string)=>(error:unknown)=>notifyError(`load ${name}`,error,ping,`${name} could not be loaded. Check your connection and permissions.`);const a=onSnapshot(collection(db,'revenueCategories'),s=>setRev(s.docs.map(d=>({id:d.id,...d.data()} as Category))),fail('Revenue categories'));const b=onSnapshot(collection(db,'expenseCategories'),s=>setExp(s.docs.map(d=>({id:d.id,...d.data()} as Category))),fail('Expense categories'));return()=>{a();b()}},[db]);
  async function create(e:FormEvent){e.preventDefault();const value=name.trim();if(value.length<2||value.length>60){ping('Category names must be 2–60 characters.');return}if(!db){ping('This app is not connected. Refresh the page or contact the administrator.');return}try{await addDoc(collection(db,kind==='revenue'?'revenueCategories':'expenseCategories'),{name:value,active:true,systemControlled:false,createdAt:serverTimestamp()});setName('');ping('Category added.')}catch(error:unknown){notifyError('create category',error,ping,'Could not add the category. Please try again.')}}
  async function toggle(c:Category,which:'revenue'|'expense'){if(!db||c.systemControlled)return;try{await updateDoc(doc(db,which==='revenue'?'revenueCategories':'expenseCategories',c.id),{active:!c.active,updatedAt:serverTimestamp()});ping(c.active?'Category archived.':'Category activated.')}catch(error:unknown){notifyError('update category',error,ping,'Could not update the category. Please try again.')}}
  function beginEdit(c:Category,which:'revenue'|'expense'){if(c.systemControlled)return;setEditing({id:c.id,kind:which,name:c.name});setEditName(c.name)}
  async function saveEdit(e:FormEvent){e.preventDefault();if(!db||!editing)return;const value=editName.trim();if(value.length<2||value.length>60){ping('Category names must be 2–60 characters.');return}try{await updateDoc(doc(db,editing.kind==='revenue'?'revenueCategories':'expenseCategories',editing.id),{name:value,updatedAt:serverTimestamp()});setEditing(null);ping('Category updated. Historical transaction snapshots are unchanged.')}catch(error:unknown){notifyError('rename category',error,ping,'Could not update the category. Please try again.')}}
  function section(title:string,items:Category[],which:'revenue'|'expense',counts:(c:string)=>number){return <div className="panel"><div className="panel-head"><div><h3>{title}</h3><p>{which==='revenue'?'Organize your event income':'Classify and track event costs'}</p></div><span className="counter">{items.filter(x=>x.active).length} ACTIVE</span></div>{items.map((c,i)=><div className="category-row" key={c.id}><span className="cat-swatch" style={{background:colors[i%colors.length]}}/><div><b>{c.name}</b><small>{c.systemControlled?'System controlled':`${counts(c.name)} transactions`}</small></div><span className={`category-state ${c.active?'':'inactive'}`}><i/>{c.active?'Active':'Archived'}</span>{!c.systemControlled&&<div className="category-actions"><button className="text-action" onClick={()=>beginEdit(c,which)}>Edit</button><button className="text-action" onClick={()=>toggle(c,which)}>{c.active?'Archive':'Activate'}</button></div>}</div>)}</div>}
  return <><div className="category-grid">{section('Revenue categories',rev,'revenue',c=>revenues.filter(x=>x.category===c).length)}{section('Expense categories',exp,'expense',c=>expenses.filter(x=>x.category===c).length)}</div><div className="panel add-category"><div><h3>Add a category</h3><p>New categories appear in future transactions.</p></div><form onSubmit={create}><select value={kind} onChange={e=>setKind(e.target.value as 'revenue'|'expense')}><option value="revenue">Revenue</option><option value="expense">Expense</option></select><input value={name} onChange={e=>setName(e.target.value)} placeholder="Category name"/><button className="btn primary"><Plus size={15}/> Add category</button></form></div><div className="callout"><span><b>Historical records stay intact.</b> Renaming stores a new category label for future records. Categories cannot be deleted; archive them instead.</span></div>{editing&&<div className="modal-overlay" onClick={()=>setEditing(null)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><div className="eyebrow">CATEGORY SETTINGS</div><h2>Edit category</h2></div><button className="icon-button" onClick={()=>setEditing(null)}><X/></button></div><form onSubmit={saveEdit}><div className="modal-body"><label>Category name<input value={editName} onChange={e=>setEditName(e.target.value)} required maxLength={60}/></label></div><div className="modal-foot"><button type="button" className="btn secondary" onClick={()=>setEditing(null)}>Cancel</button><button className="btn primary">Save changes</button></div></form></div></div>}</>
}
