import {useState,type FormEvent} from 'react';
import {doc,runTransaction,serverTimestamp} from 'firebase/firestore';
import {db} from '../firebase';
import type {Tier} from '../types';
import {parseNaira} from '../money';
import {notifyError,userFacingError} from '../errorHandling';

export default function TicketTierEditor({tiers,actor,actorId,onClose,ping}:{tiers:Tier[];actor:string;actorId:string;onClose:()=>void;ping:(message:string)=>void}){
  const [rows,setRows]=useState(tiers.map(x=>({id:x.id,name:x.name,price:String(x.price),capacity:String(x.capacity),sold:x.sold})));const [busy,setBusy]=useState(false);
  async function save(e:FormEvent){e.preventDefault();if(!db){ping('This app is not connected. Refresh the page or contact the administrator.');return}const firestore=db,auditId=crypto.randomUUID();setBusy(true);try{const next=rows.map(x=>({id:x.id,price:parseNaira(x.price),capacity:parseNaira(x.capacity)}));if(next.reduce((n,x)=>n+x.capacity,0)!==700)throw userFacingError('Ticket capacities must add up to 700.');await runTransaction(firestore,async tx=>{const refs=next.map(x=>doc(firestore,'ticketTiers',x.id)),snapshots=await Promise.all(refs.map(ref=>tx.get(ref)));if(snapshots.some(s=>!s.exists()))throw userFacingError('Ticket tiers are not available. Refresh the page and try again.');next.forEach((x,i)=>{const sold=Number(snapshots[i].data()?.sold||0);if(x.capacity<sold)throw userFacingError('Capacity cannot be lower than tickets already sold.');tx.update(refs[i],{price:x.price,capacity:x.capacity,updatedAt:serverTimestamp()})});tx.set(doc(firestore,'settings','workspace'),{auditLogId:auditId,updatedAt:serverTimestamp()},{merge:true});tx.set(doc(firestore,'activityLogs',auditId),{actor,actorId,action:'configuration.updated',label:'configuration.updated',targetType:'settings',targetId:'workspace',createdAt:serverTimestamp()})});ping('Ticket tiers updated.');onClose();}catch(error:unknown){notifyError('save ticket tiers',error,ping,'Could not update ticket tiers. Please try again.');}finally{setBusy(false)}}
  return <div className="modal-overlay" onClick={onClose}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><div className="eyebrow">ADMIN CONTROLS</div><h2>Edit ticket tiers</h2></div><button className="icon-button" type="button" onClick={onClose}>×</button></div><form onSubmit={save}><div className="modal-body"><p className="small-note">Capacity must total 700. Existing sales and historical prices are preserved.</p>{rows.map((row,i)=><div className="ticket-edit-row" key={row.id}><b>{row.name}<small>{row.sold} sold</small></b><label>Price (₦)<input type="number" min="0" step="1" value={row.price} onChange={e=>setRows(old=>old.map((x,j)=>j===i?{...x,price:e.target.value}:x))}/></label><label>Capacity<input type="number" min={row.sold} step="1" value={row.capacity} onChange={e=>setRows(old=>old.map((x,j)=>j===i?{...x,capacity:e.target.value}:x))}/></label></div>)}</div><div className="modal-foot"><button type="button" className="btn secondary" onClick={onClose}>Cancel</button><button disabled={busy} className="btn primary">{busy?'Saving…':'Save tiers'}</button></div></form></div></div>
}
