import {useEffect,useState,useRef,useMemo} from 'react'; import {onAuthStateChanged,signInWithEmailAndPassword,signOut,sendEmailVerification,sendPasswordResetEmail,reload,getIdToken} from 'firebase/auth'; import {collection,doc,onSnapshot,serverTimestamp,query,orderBy,limit,getDoc,runTransaction,writeBatch} from 'firebase/firestore'; import {Activity,ArrowDownRight,ArrowUpRight,BarChart3, Bell, ChevronDown, CircleDollarSign, Download, LayoutDashboard, LogOut, Menu, Plus, Search, ShieldCheck, Ticket, Users, Wallet, X} from 'lucide-react'; import {Doughnut,Bar} from 'react-chartjs-2'; import {Chart as ChartJS,ArcElement,Tooltip,Legend,CategoryScale,LinearScale,BarElement} from 'chart.js'; import {auth,db,configured,localFirebaseMode,useFirebaseEmulators} from './firebase'; import {formatNaira,parseNaira} from './money'; import BudgetEditor from './components/BudgetEditor'; import TicketTierEditor from './components/TicketTierEditor'; import type {Allocation,Expense,Person,Revenue,Role,Tier} from './types';
import {getExpenseBudgetWarnings,summarizeAllocationExpenses,summarizeExpenses} from './budget';
import {canClaimMasterAdmin,canManageFinancialRecords,canRecordTicketSales,MASTER_ADMIN_EMAIL as MASTER_EMAIL} from './accessControl.mjs';
import {notifyError,userFacingError} from './errorHandling';
import {recordTicketSale,type TicketSaleAttempt} from './ticketSales.mjs';
import {recordExpense,type ExpenseAttempt} from './financialWrites.mjs';
import CategoriesManager from './components/Categories';
import DashboardSkeleton from './components/DashboardSkeleton';
import AccountSetupRecovery from './components/AccountSetupRecovery';
import OverviewDashboard from './components/OverviewDashboard';
import ReportsPage from './components/Reports';
import ActivityPage from './components/ActivityPage';
import AppFooter from './components/AppFooter';
import BrandLogo from './components/BrandLogo';
import PoweredBy from './components/PoweredBy';
import {buildReportCsv,buildReportView} from './reporting';
import {summarizeDashboard} from './dashboard';
import {createGuestAccount,repairGuestAccountProfile,SignupSetupError} from './signup.mjs';
ChartJS.register(ArcElement,Tooltip,Legend,CategoryScale,LinearScale,BarElement);
const seedTiers:Tier[]=[{id:'early-bird',name:'Early Bird',price:5000,capacity:150,sold:0,active:true},{id:'regular',name:'Regular',price:8000,capacity:540,sold:0,active:true},{id:'vip-experience',name:'VIP Experience',price:150000,capacity:10,sold:0,active:true}];
const seedRevs:Revenue[]=[];
const seedExps:Expense[]=[];
const seedAlloc:Allocation[]=[];
type Page='Overview'|'Tickets'|'Revenues'|'Expenses'|'Budget'|'Categories'|'Reports'|'User management'|'Activity log';
const nav:{name:Page;icon:any;group:string}[]=[{name:'Overview',icon:LayoutDashboard,group:'WORKSPACE'},{name:'Tickets',icon:Ticket,group:'WORKSPACE'},{name:'Revenues',icon:ArrowUpRight,group:'WORKSPACE'},{name:'Expenses',icon:ArrowDownRight,group:'WORKSPACE'},{name:'Budget',icon:Wallet,group:'WORKSPACE'},{name:'Categories',icon:BarChart3,group:'MANAGE'},{name:'Reports',icon:Download,group:'MANAGE'},{name:'User management',icon:Users,group:'MANAGE'},{name:'Activity log',icon:Activity,group:'MANAGE'}];
const palette=['#00F5FF','#FF2BD6','#B6FF00','#7C69FF','#FFB547'];
const financeAuditFields=['title','category','budgetAllocationId','amount','status','date','method','agent','createdBy'] as const;
function auditFieldValue(record:Record<string,unknown>,field:string){return Object.prototype.hasOwnProperty.call(record,field)?{present:true,value:record[field]}:{present:false}}
function financeAuditChanges(before:Record<string,unknown>,after:Record<string,unknown>){const changes:Record<string,unknown>={};for(const field of financeAuditFields){const oldValue=auditFieldValue(before,field),newValue=auditFieldValue(after,field);if(oldValue.present!==newValue.present||oldValue.present&&newValue.present&&!Object.is(oldValue.value,newValue.value))changes[field]={before:oldValue,after:newValue}}return changes}
function financeAuditSnapshot(record:Record<string,unknown>){const snapshot:Record<string,unknown>={};for(const field of financeAuditFields)if(Object.prototype.hasOwnProperty.call(record,field))snapshot[field]=record[field];return snapshot}
function timeGreeting(date=new Date()){const hour=date.getHours();if(hour>=5&&hour<12)return 'Good Morning';if(hour>=12&&hour<17)return 'Good Afternoon';if(hour>=17&&hour<21)return 'Good Evening';return 'Good Night'}
export default function App(){
 const [page,setPage]=useState<Page>('Overview'),[user,setUser]=useState<Person|null>(null),[profileRepairAuth,setProfileRepairAuth]=useState<any|null>(null),[tiers,setTiers]=useState(seedTiers),[ticketSales,setTicketSales]=useState<any[]>([]),[revenues,setRevenues]=useState(seedRevs),[expenses,setExpenses]=useState(seedExps),[allocations,setAllocations]=useState(seedAlloc),[budgetInfo,setBudgetInfo]=useState<any>(null),[revenueCategories,setRevenueCategories]=useState<string[]>(['Bar & Merch Sales','Sponsorships','Vendor Booth Fees','Support / Donations']),[expenseCategories,setExpenseCategories]=useState<string[]>(['Talent & Booking','Venue & Production','Marketing & Promo','Operations & Safety']),[logs,setLogs]=useState<any[]>([]),[modal,setModal]=useState(''),[editRecord,setEditRecord]=useState<any>(null),[mobile,setMobile]=useState(false),[toast,setToast]=useState(''),[queryText,setQueryText]=useState(''),[authMode,setAuthMode]=useState('login'),[busy,setBusy]=useState(false),[authReady,setAuthReady]=useState(!auth);
  const [reportStart,setReportStart]=useState(''),[reportEnd,setReportEnd]=useState('');
  const logsCursor=useRef<any>(null);
  const pendingTicketSale=useRef<{key:string;attempt:TicketSaleAttempt}|null>(null);
  const pendingExpense=useRef<{key:string;attempt:ExpenseAttempt}|null>(null);
  const submittingRecord=useRef(false);
  const authProfileRef=useRef<Person|null>(null);
  function clearFinancialData(){setTicketSales([]);setRevenues(seedRevs);setExpenses(seedExps);setAllocations(seedAlloc);setBudgetInfo(null);setRevenueCategories(['Bar & Merch Sales','Sponsorships','Vendor Booth Fees','Support / Donations']);setExpenseCategories(['Talent & Booking','Venue & Production','Marketing & Promo','Operations & Safety']);}
  function clearAccountData(){authProfileRef.current=null;setTiers(seedTiers);clearFinancialData();setLogs([]);logsCursor.current=null;setPage('Overview');setModal('');setEditRecord(null);}
  useEffect(()=>{if(!auth||!db)return;let active=true,generation=0;let stopProfile:(()=>void)|undefined;const currentAuth=auth;const isCurrent=(uid:string,requestGeneration:number)=>active&&generation===requestGeneration&&currentAuth.currentUser?.uid===uid;const stop=onAuthStateChanged(currentAuth,fu=>{const requestGeneration=++generation;stopProfile?.();stopProfile=undefined;if(!fu){if(active){clearAccountData();setUser(null);setProfileRepairAuth(null);setAuthReady(true)}return}if(active){clearAccountData();setUser(null);setProfileRepairAuth(null);setAuthReady(false)}void(async()=>{try{await getIdToken(fu,true);if(!isCurrent(fu.uid,requestGeneration))return;stopProfile=onSnapshot(doc(db!,'users',fu.uid),{includeMetadataChanges:true},snap=>{if(!isCurrent(fu.uid,requestGeneration)||snap.metadata.fromCache)return;if(!snap.exists()){clearAccountData();setUser(null);setProfileRepairAuth(fu);setAuthReady(true);return}const profile=snap.data() as Person,previous=authProfileRef.current;setProfileRepairAuth(null);authProfileRef.current=profile;setUser(profile);if(profile.status!=='approved'){setTiers(seedTiers);clearFinancialData();setLogs([]);setPage('Overview');setModal('');setEditRecord(null)}else{if(profile.role!=='admin'&&profile.role!=='executive'&&profile.role!=='member'&&profile.role!=='guest')clearFinancialData();if(profile.role!=='admin'){setLogs([]);logsCursor.current=null;}if(previous&&(previous.status!==profile.status||previous.role!==profile.role))setPage('Overview')}setAuthReady(true)},error=>{if(!isCurrent(fu.uid,requestGeneration))return;clearAccountData();setUser(null);setProfileRepairAuth(null);setAuthReady(true);notifyError('monitor account profile',error,ping,'Could not monitor your account access. Sign in again or contact the administrator.')})}catch(error:unknown){if(!isCurrent(fu.uid,requestGeneration))return;clearAccountData();setUser(null);setProfileRepairAuth(null);setAuthReady(true);notifyError('load account profile',error,ping,'Could not load your account. Check your connection and sign in again.')}})()},error=>{if(active){generation++;stopProfile?.();stopProfile=undefined;clearAccountData();setUser(null);setAuthReady(true);notifyError('monitor sign-in state',error,ping,'Could not check your sign-in state. Reload the app and try again.')}});return()=>{active=false;generation++;stopProfile?.();stop()}},[]);useEffect(()=>{
  if(!user||!auth)return;
  const currentAuth=auth,timeout=10*60*1000;
  let lastActivity=Date.now(),timer=0,disposed=false;
  const expire=async()=>{if(disposed)return;try{await signOut(currentAuth);ping('Signed out after 10 minutes of inactivity.')}catch(error:unknown){notifyError('automatic sign out',error,ping,'Could not sign out after inactivity. Select Sign out and try again.')}};
  const schedule=(delay=timeout)=>{window.clearTimeout(timer);timer=window.setTimeout(()=>{const remaining=timeout-(Date.now()-lastActivity);if(remaining<=0)void expire();else schedule(remaining)},delay)};
  const activity=()=>{lastActivity=Date.now();schedule()};
  const checkAfterTabReturn=()=>{if(document.visibilityState==='visible'){const remaining=timeout-(Date.now()-lastActivity);if(remaining<=0)void expire();else schedule(remaining)}};
  const events=['pointerdown','pointermove','keydown','touchstart','wheel'] as const;
  events.forEach(type=>window.addEventListener(type,activity,{passive:true}));
  document.addEventListener('visibilitychange',checkAfterTabReturn);
  schedule();
  return()=>{disposed=true;window.clearTimeout(timer);events.forEach(type=>window.removeEventListener(type,activity));document.removeEventListener('visibilitychange',checkAfterTabReturn)};
},[user?.uid,user?.role,user?.status]);useEffect(()=>{if(!db||!user?.uid||user.status!=='approved')return;const canReadCurrentProfile=()=>{const profile=authProfileRef.current;return profile?.uid===user.uid&&profile.status==='approved'};const canReadFinance=()=>{const profile=authProfileRef.current;return canReadCurrentProfile()&&(profile?.role==='admin'||profile?.role==='executive'||profile?.role==='member'||profile?.role==='guest')};const canReadAdmin=()=>canReadCurrentProfile()&&authProfileRef.current?.role==='admin';const fail=(label:string,allowed:()=>boolean)=>(error:unknown)=>{if(allowed())notifyError(`load ${label}`,error,ping,`${label} could not be loaded. Check your connection and permissions.`)};const stops:Array<()=>void>=[onSnapshot(collection(db,'ticketTiers'),s=>{if(canReadFinance())setTiers(s.docs.map(d=>({id:d.id,...d.data()} as Tier)))},fail('Ticket data',canReadFinance))];if(user.role==='admin'||user.role==='executive'||user.role==='member'||user.role==='guest'){stops.push(onSnapshot(query(collection(db,'ticketSales'),orderBy('createdAt','desc')),s=>{if(canReadFinance())setTicketSales(s.docs.map(d=>({id:d.id,...d.data()})))},fail('Ticket ledger',canReadFinance)),onSnapshot(query(collection(db,'revenues'),orderBy('date','desc')),s=>{if(canReadFinance())setRevenues(s.docs.map(d=>({id:d.id,...d.data()} as Revenue)))},fail('Revenue data',canReadFinance)),onSnapshot(query(collection(db,'expenses'),orderBy('date','desc')),s=>{if(canReadFinance())setExpenses(s.docs.map(d=>({id:d.id,...d.data()} as Expense)))},fail('Expense data',canReadFinance)),onSnapshot(doc(db,'budgets','event-2026'),s=>{if(canReadFinance())setBudgetInfo(s.exists()?s.data():null)},fail('Event budget',canReadFinance)),onSnapshot(collection(db,'budgetAllocations'),s=>{if(canReadFinance())setAllocations(s.docs.map(d=>({id:d.id,...d.data()} as Allocation)))},fail('Budget data',canReadFinance)),onSnapshot(collection(db,'revenueCategories'),s=>{if(canReadFinance())setRevenueCategories(s.docs.filter(d=>d.data().active!==false&&!d.data().systemControlled).map(d=>String(d.data().name)))},fail('Revenue categories',canReadFinance)),onSnapshot(collection(db,'expenseCategories'),s=>{if(canReadFinance())setExpenseCategories(s.docs.filter(d=>d.data().active!==false).map(d=>String(d.data().name)))},fail('Expense categories',canReadFinance)));if(user.role==='admin')stops.push(onSnapshot(query(collection(db,'activityLogs'),orderBy('createdAt','desc'),limit(40)),s=>{if(canReadAdmin()){logsCursor.current=s.docs.at(-1)??null;setLogs(s.docs.map(d=>({id:d.id,...d.data()})))}},fail('Activity log',canReadAdmin)))}return()=>stops.forEach(stop=>stop())},[user?.uid,user?.role,user?.status]);
 useEffect(()=>{if(!db||user?.role!=='admin')return;void initializeWorkspace().catch((error:unknown)=>notifyError('initialize event workspace',error,ping,'Event setup could not be completed. Refresh the page or contact support.'));},[user?.role]);
 const role=user?.role??null,admin=role==='admin',financeReader=role==='admin'||role==='executive'||role==='member'||role==='guest',displayName=user?.fullName||'User',displayUid=user?.uid||'',budget=Number(budgetInfo?.totalAmount)||allocations.reduce((a,x)=>a+x.amount,0);const dashboardSummary=useMemo(()=>summarizeDashboard({revenues,ticketSales,expenses,tiers,allocations,totalBudget:budget}),[revenues,ticketSales,expenses,tiers,allocations,budget]);const reportView=useMemo(()=>buildReportView({revenues,expenses,ticketSales,tiers,allocations,totalBudget:budget,startDate:reportStart,endDate:reportEnd}),[revenues,expenses,ticketSales,tiers,allocations,budget,reportStart,reportEnd]);const paidExpense=dashboardSummary.paidExpense,sold=dashboardSummary.ticketsSold;const filteredRev=revenues.filter(x=>(x.title+' '+x.category+' '+x.agent).toLowerCase().includes(queryText.toLowerCase()));const filteredExp=expenses.filter(x=>(x.title+' '+x.category+' '+x.agent).toLowerCase().includes(queryText.toLowerCase()));const budgetExpenseCategories=[...new Set([...expenseCategories,...allocations.map(a=>a.category)])];
  const toastTimer=useRef<number|undefined>(undefined);const ping=(s:string)=>{window.clearTimeout(toastTimer.current);setToast(s);toastTimer.current=window.setTimeout(()=>setToast(''),5000)};useEffect(()=>()=>window.clearTimeout(toastTimer.current),[]);
  async function logout(){if(!auth)return;try{await signOut(auth)}catch(error:unknown){notifyError('sign out',error,ping,'Could not sign out. Try again.') }}
  function auditEntry(action:string,targetType:string,targetId:string,details:Record<string,unknown>={}){if(!user)throw userFacingError('Your session is unavailable. Sign in again and retry.');return {actor:user.fullName,actorId:user.uid,action,label:action,targetType,targetId,createdAt:serverTimestamp(),...details}}
  async function initializeWorkspace(){if(!db||!user||user.role!=='admin')return;const firestore=db;const tiers=seedTiers.map(t=>({id:t.id,data:{...t,isCapped:true,isActive:true}})),expCats=[['talent-booking','Talent & Booking','Talent, artist and booking costs'],['venue-production','Venue & Production','Venue, staging and production'],['marketing-promo','Marketing & Promo','Campaigns and promotion'],['operations-safety','Operations & Safety','Operations, medical and security']],revCats=[['ticket-sales','Ticket Sales','',true],['bar-merch-sales','Bar & Merch Sales','',false],['sponsorships','Sponsorships','',false],['vendor-booth-fees','Vendor Booth Fees','',false],['support-donations','Support / Donations','',false]],entries:any[]=[...tiers.map(x=>({path:`ticketTiers/${x.id}`,data:{...x.data,sold:0,active:true}})),...expCats.map(([id,name,description])=>({path:`expenseCategories/${id}`,data:{name,description,active:true}})),...revCats.map(([id,name,,systemControlled])=>({path:`revenueCategories/${id}`,data:{name,active:true,systemControlled}})),{path:'settings/budgetControl',data:{mode:'warn'}},{path:'settings/eventCapacity',data:{total:700}}];await runTransaction(firestore,async(transaction)=>{const refs=entries.map(x=>doc(firestore,x.path));const snapshots=await Promise.all(refs.map(ref=>transaction.get(ref)));const missing=entries.map((entry,index)=>({entry,ref:refs[index],snapshot:snapshots[index]})).filter(x=>!x.snapshot.exists());if(!missing.length)return;const auditId=crypto.randomUUID();for(const {entry,ref} of missing)transaction.set(ref,{...entry.data,auditLogId:auditId,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});transaction.set(doc(firestore,'settings','workspace'),{auditLogId:auditId,updatedAt:serverTimestamp()},{merge:true});transaction.set(doc(firestore,'activityLogs',auditId),{actor:user.fullName,actorId:user.uid,action:'configuration.updated',label:'configuration.updated',targetType:'settings',targetId:'workspace',createdAt:serverTimestamp()})})}
  async function login(e:any){e.preventDefault();setBusy(true);try{if(!auth)throw userFacingError('Connect Firebase to enable sign in.');await signInWithEmailAndPassword(auth,e.currentTarget.email.value,e.currentTarget.password.value);}catch(error:unknown){notifyError('sign in',error,ping,'Could not sign in. Check your details and try again.')}finally{setBusy(false)}}
  async function resetPassword(email:string){try{if(!auth)throw userFacingError('Password reset is temporarily unavailable. Please contact the administrator.');if(!email.trim())throw userFacingError('Enter your email address first.');await sendPasswordResetEmail(auth,email.trim());ping("Password reset email sent.")}catch(error:unknown){notifyError('send password reset',error,ping,'Could not send the reset email. Check the address and try again.')}} async function signup(e:any){e.preventDefault();setBusy(true);try{if(!auth||!db)throw userFacingError('Account registration is temporarily unavailable. Contact the administrator.');const form=e.currentTarget,fullName=String(form.fullName.value||'').trim(),username=String(form.username.value||'').trim().toLowerCase(),email=String(form.email.value||'').trim().toLowerCase(),password=String(form.password.value||'');if(fullName.length<2||fullName.length>100)throw userFacingError('Enter a name between 2 and 100 characters.');if(!/^[a-z0-9_-]{3,24}$/.test(username)||['admin','slkadmin','administrator'].includes(username))throw userFacingError('Choose a 3–24 character username using letters, numbers, _ or -.');if(password.length<8)throw userFacingError('Choose a password with at least 8 characters.');if(password!==String(form.confirm.value||''))throw userFacingError('Passwords do not match.');const {credential,profile}=await createGuestAccount({auth,db,fullName,username,email,password});setUser(profile);try{await sendEmailVerification(credential.user);ping('Account created. Check your email to verify it.')}catch(error:unknown){notifyError('send verification email',error,ping,'Your account is ready, but the verification email could not be sent. Use Resend verification or contact the administrator.')}}catch(error:unknown){if(error instanceof SignupSetupError){if(error.state==='cleanup-failed'&&error.user&&auth?.currentUser?.uid===error.user.uid){clearAccountData();setUser(null);setProfileRepairAuth(error.user);setAuthReady(true);ping('Your sign-in exists, but setup needs one more step. Complete Guest account setup below.')}else{notifyError('create account',userFacingError(error.state==='rolled-back'?'Account setup did not complete and your unused sign-in was removed. Try again with a different username or retry.':'Account setup did not complete, and we could not safely confirm or remove the sign-in. Do not register again; contact the administrator for help.'),ping)}}else notifyError('create account',error,ping,'Could not create the account. Check your details and try again.')}finally{setBusy(false)}}
 async function finishProfileSetup(details:{fullName:string;username:string}){if(!auth?.currentUser||!db){ping('Your session is unavailable. Sign in again and retry.');return}setBusy(true);try{const profile=await repairGuestAccountProfile({auth,db,...details});authProfileRef.current=profile;setProfileRepairAuth(null);setUser(profile);ping('Account setup completed.')}catch(error:unknown){notifyError('complete account setup',error,ping,'Could not complete account setup. Check the username and try again.')}finally{setBusy(false)}} async function resendVerification(){if(!auth?.currentUser){ping('Sign in again to resend the verification email.');return}try{await sendEmailVerification(auth.currentUser);ping('Verification email sent. Check your inbox and spam folder.')}catch(error:unknown){notifyError('resend verification email',error,ping,'Could not resend the verification email. Wait a moment and try again.')}}async function claimMaster(){if(!auth?.currentUser||!db){ping('Your session is unavailable. Sign in again and retry.');return}setBusy(true);try{await reload(auth.currentUser);await getIdToken(auth.currentUser,true);if(!auth.currentUser.emailVerified)throw userFacingError('Verify the Master Admin email first, then try again.');const userRef=doc(db,'users',auth.currentUser.uid),profile=await getDoc(userRef);if(!profile.exists())throw userFacingError('Your account profile is incomplete. Contact the administrator for help.');if(String(profile.data().email||'').toLowerCase()!==MASTER_EMAIL)throw userFacingError('This account is not eligible for Master Admin access.');const auditId=crypto.randomUUID(),batch=writeBatch(db);batch.update(userRef,{status:'approved',role:'admin',isMasterAdmin:true,auditLogId:auditId,updatedAt:serverTimestamp()});batch.set(doc(db,'usersPublic',auth.currentUser.uid),{status:'approved',role:'admin',auditLogId:auditId,updatedAt:serverTimestamp()},{merge:true});batch.set(doc(db,'settings','masterAdmin'),{uid:auth.currentUser.uid,email:MASTER_EMAIL,createdAt:serverTimestamp()});batch.set(doc(db,'activityLogs',auditId),{actor:profile.data().fullName,actorId:auth.currentUser.uid,action:'user.master_admin_claimed',label:'user.master_admin_claimed',targetType:'users',targetId:auth.currentUser.uid,createdAt:serverTimestamp()});await batch.commit();const snap=await getDoc(userRef);if(snap.exists())setUser(snap.data() as Person);ping('Master Admin access activated.')}catch(error:unknown){notifyError('activate Master Admin',error,ping,'Could not activate Master Admin access. Refresh the page and try again.')}finally{setBusy(false)}}async function submitRecord(e:any){
    e.preventDefault();
    if(submittingRecord.current||busy)return;
    submittingRecord.current=true;
    const form=e.currentTarget,kind=modal;
    if(!db||!user){submittingRecord.current=false;ping('Your session is unavailable. Sign in again and retry.');return;}
    if((kind==='expense'||kind==='revenue')&&!canManageFinancialRecords(user.role)){
      submittingRecord.current=false;
      ping('You have read-only access to financial records.');
      return;
    }
    if(kind==='ticket'&&!canRecordTicketSales(user.role)){
      submittingRecord.current=false;
      ping('Your account cannot record ticket sales.');
      return;
    }
    setBusy(true);
    try{
      const date=String(form.date.value||new Date().toISOString().slice(0,10)),category=String(form.category?.value||'');
      if(kind==='ticket'){
        const tierId=String(form.tier.value||''),quantity=Number(form.quantity.value);
        if(!Number.isInteger(quantity)||quantity<1||quantity>20)throw userFacingError('Ticket quantity must be a whole number from 1 to 20.');
        if(!tierId)throw userFacingError('Select an available ticket tier.');
        const quotedUnitPrice=Number(form.quotedUnitPrice.value),key=JSON.stringify([user.uid,tierId,quantity,date,quotedUnitPrice]);
        let pending=pendingTicketSale.current;
        if(!pending||pending.key!==key){pending={key,attempt:{saleId:doc(collection(db,'ticketSales')).id,auditId:doc(collection(db,'activityLogs')).id,tierId,quantity,date,quotedUnitPrice}};pendingTicketSale.current=pending}
        const result=await recordTicketSale(db,pending.attempt,user.fullName,user.uid,userFacingError);
        if(pendingTicketSale.current===pending)pendingTicketSale.current=null;
        ping(result==='already-recorded'?'Ticket sale was already recorded.':'Ticket sale recorded.');
      }else if(kind==='expense'||kind==='revenue'){
        const title=String(form.title.value||'').trim(),amount=parseNaira(String(form.amount.value||''));
        if(!title||title.length>160)throw userFacingError('Enter a description of up to 160 characters.');
        if(amount<=0)throw userFacingError('Amount must be greater than zero.');
        if(!category)throw userFacingError('Select a category.');
        const status=String(form.status.value||'Paid');
        if(!(kind==='expense'?['Paid','Pending','Deposit',...(editRecord?.status==='Unpaid'?['Unpaid']:[])]:['Paid','Pending','Unpaid']).includes(status))throw userFacingError('Choose a valid payment status.');
        const reason=String(form.reason?.value||'').trim(),reasonRequired=Boolean(editRecord)&&(Number(editRecord.amount)!==amount||String(editRecord.status)!==status);
        if(reason.length>500)throw userFacingError('Reason must be 500 characters or fewer.');
        if(reasonRequired&&!reason)throw userFacingError('Enter a reason when changing the amount or payment status.');
        const allocation=kind==='expense'?allocations.find((item:any)=>item.category===category):undefined,coll=kind==='expense'?'expenses':'revenues';
        const payload=kind==='expense'?{title,category,budgetAllocationId:allocation?.id||null,amount,status,date,updatedBy:user.uid,updatedAt:serverTimestamp()}:{title,category,amount,status,date,method:String(form.method?.value||'Other'),agent:user.fullName,createdBy:user.uid,updatedBy:user.uid,updatedAt:serverTimestamp()};
        if(kind==='expense'&&!editRecord){
          const key=JSON.stringify([user.uid,title,category,allocation?.id||null,amount,status,date]);
          let pending=pendingExpense.current;
          if(!pending||pending.key!==key){
            pending={key,attempt:{expenseId:doc(collection(db,'expenses')).id,auditId:doc(collection(db,'activityLogs')).id,title,category,budgetAllocationId:allocation?.id||null,amount,status:status as ExpenseAttempt['status'],date}};
            pendingExpense.current=pending;
          }
          const result=await recordExpense(db,pending.attempt,user.fullName,user.uid,userFacingError);
          if(pendingExpense.current===pending)pendingExpense.current=null;
          ping(result==='already-recorded'?'Expense was already recorded.':'Expense saved.');
        }else{
        const recordRef=editRecord?doc(db,coll,editRecord.id):doc(collection(db,coll)),activityRef=doc(collection(db,'activityLogs')),action=`${kind}.${editRecord?'updated':'created'}`;
        if(editRecord){await runTransaction(db,async(transaction)=>{const current=await transaction.get(recordRef);if(!current.exists())throw userFacingError('This record no longer exists. Refresh the ledger and try again.');const before=current.data() as Record<string,unknown>,changes=financeAuditChanges(before,payload),amountCorrected=kind==='expense'&&!Object.is(before.amount,payload.amount),sensitiveChange=!Object.is(before.amount,payload.amount)||!Object.is(before.status,payload.status);if(sensitiveChange&&!reason)throw userFacingError('Enter a reason when changing the amount or payment status.');const auditDetails={changes,...(amountCorrected?{previousAmount:before.amount,newAmount:payload.amount}:{}),...(reason?{reason}:{})};transaction.update(recordRef,{...payload,...(amountCorrected?{previousAmount:before.amount}:{}),auditLogId:activityRef.id});transaction.set(activityRef,auditEntry(action,coll,recordRef.id,auditDetails));})}
        else{const batch=writeBatch(db);batch.set(recordRef,{...payload,auditLogId:activityRef.id,...(kind==='expense'?{method:'Other',agent:user.fullName,createdBy:user.uid}:{}),createdAt:serverTimestamp()});batch.set(activityRef,auditEntry(action,coll,recordRef.id,{...(reason?{reason}:{})}));await batch.commit()}
        }
        const budgetWarnings=kind==='expense'?getExpenseBudgetWarnings(expenses,allocations,budget,{...payload,id:editRecord?.id},editRecord?.id):[];
        if(budgetWarnings.length)ping('Expense saved. '+budgetWarnings.join(' '));
        else if(editRecord)ping('Record updated.');
        else if(kind==='revenue')ping('Record saved.');
        setEditRecord(null);
      }else throw userFacingError('This form is no longer available. Close it and try again.');
      setModal('');
    }catch(error:unknown){notifyError('save record',error,ping,'Could not save the record. Check the values and try again.');}
    finally{submittingRecord.current=false;setBusy(false);}
  }function editFinancialRecord(kind:'expense'|'revenue',row:any){setEditRecord({...row,kind});setModal(kind)}
  async function deleteFinancialRecord(kind:'expense'|'revenue',row:any){if(!db||!user||user.role!=='admin'){ping('Only Admins can delete financial records.');return}const entered=window.prompt('Enter a reason for deleting this financial record (required, up to 500 characters):');if(entered===null)return;const reason=entered.trim();if(!reason||reason.length>500){ping('Enter a reason of 1–500 characters to delete this record.');return}if(!window.confirm('Delete “'+row.title+'”? This keeps the action, reason, and record details in the audit log.'))return;try{const targetType=kind==='expense'?'expenses':'revenues',recordRef=doc(db,targetType,row.id),activityRef=doc(db,'activityLogs',row.id);await runTransaction(db,async(transaction)=>{const current=await transaction.get(recordRef);if(!current.exists())throw userFacingError('This record no longer exists. Refresh the ledger.');transaction.delete(recordRef);transaction.set(activityRef,auditEntry(kind+'.deleted',targetType,row.id,{reason,snapshot:financeAuditSnapshot(current.data() as Record<string,unknown>)}))});ping('Record deleted.')}catch(error:unknown){notifyError('delete record',error,ping,'Could not delete the record. Refresh and try again.')}}
 async function approval(uid:string,action:'approve'|'reject'|'role'|'suspend'|'reactivate',newRole:Role,reason?:string){if(!db||!user)return;const normalizedReason=String(reason||'').trim(),reasonRequired=['approve','role','suspend','reactivate'].includes(action);if(reasonRequired&&!normalizedReason){ping('Enter a reason for this access change.');return}if(normalizedReason.length>500){ping('Reason must be 500 characters or fewer.');return}try{const status=action==='approve'||action==='reactivate'?'approved':action==='reject'?'rejected':action==='suspend'?'suspended':undefined,auditId=crypto.randomUUID(),patch:any={updatedAt:serverTimestamp(),auditLogId:auditId};if(status)patch.status=status;if(action==='approve'||action==='role')patch.role=newRole;const batch=writeBatch(db);batch.update(doc(db,'users',uid),patch);batch.update(doc(db,'usersPublic',uid),patch);batch.set(doc(db,'activityLogs',auditId),auditEntry('user.'+action,'users',uid,normalizedReason?{reason:normalizedReason}:{}));await batch.commit();ping('User updated.')}catch(error:unknown){notifyError('update user access',error,ping,'Could not update user access. Refresh and try again.')}} function exportCsv(){if(reportView.error){notifyError("export report",userFacingError(reportView.error),ping);return}try{const csv=buildReportCsv(reportView),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const start=reportStart||"all-dates",end=reportEnd||"all-dates";a.download="SLK_Rave_Report_"+start+"_to_"+end+"_"+new Date().toISOString().slice(0,10)+".csv";a.click();URL.revokeObjectURL(a.href)}catch(error:unknown){notifyError("export report",error,ping,"Could not export the report. Please try again.")}}
 if(!authReady)return <DashboardSkeleton/>;if(!user)return profileRepairAuth?<AccountSetupRecovery fullName={profileRepairAuth.displayName||''} email={profileRepairAuth.email||''} busy={busy} submit={finishProfileSetup} logout={logout}/>:<AuthScreen mode={authMode} setMode={setAuthMode} login={login} signup={signup} busy={busy} configured={configured} localDev={localFirebaseMode} useEmulators={useFirebaseEmulators} reset={resetPassword} toast={toast} />;
 if(user&&(user.status==='pending'||user.status==='rejected'||user.status==='suspended'))return <div className="pending">{toast&&<div className="toast" role="alert"><span/> {toast}</div>}<div className="pending-content"><BrandLogo className="pending-brand-logo"/><ShieldCheck size={40}/><h1>{user.status==='pending'?'ACCESS REQUESTED':user.status==='rejected'?'REQUEST DECLINED':'ACCESS PAUSED'}</h1><p>{user.status==='pending'?(user.email?.toLowerCase()===MASTER_EMAIL?'Verify your Master Admin email, then activate the account below.':'Your account is awaiting approval from an SLK Rave administrator.'):user.status==='rejected'?'Your access request was declined. Please contact the event administrator.':'Your account is currently suspended. Contact the event administrator for help.'}</p>{user.status==='pending'&&auth?.currentUser&&!auth.currentUser.emailVerified&&<button className="btn secondary" disabled={busy} onClick={resendVerification}>Resend verification email</button>}{user.status==='pending'&&user.email?.toLowerCase()===MASTER_EMAIL&&<button className="btn primary" disabled={busy} onClick={claimMaster}>{busy?'Activating…':'I verified — activate Master Admin'}</button>}<button className="btn secondary" onClick={logout}>Sign out</button></div><AppFooter /></div>;
 return <div className="shell"><aside className={`sidebar ${mobile?'open':''}`}><div className="brand"><BrandLogo /><div><b>SLK RAVE</b><small>FINANCE CENTER</small></div><button className="icon-button close-mobile" onClick={()=>setMobile(false)}><X/></button></div><div className="event-switch"><div className="event-icon">◈</div><div><b>SLK Rave 2026</b><small>Event workspace</small></div><ChevronDown size={15}/></div>{['WORKSPACE','MANAGE'].map(g=><section className="navgroup" key={g}><label>{g}</label>{nav.filter(n=>n.group===g&&(['Overview','Tickets'].includes(n.name)||(n.name==='Budget'&&financeReader)||(['Revenues','Expenses','Reports'].includes(n.name)&&financeReader)||(n.name==='Categories'&&admin)||(n.name==='User management'&&admin)||(n.name==='Activity log'&&admin))).map(n=><button key={n.name} className={`navitem ${page===n.name?'active':''}`} onClick={()=>{setPage(n.name);setMobile(false)}}><n.icon size={17}/><span>{n.name}</span>{n.name==='Overview'&&<i/>}</button>)}</section>)}<div className="sidebar-bottom"><div className="live"><span className="pulse"/>LIVE DATA SYNC</div><div className="profile"><div className="avatar">{displayName.slice(0,1).toUpperCase()}</div><div className="profile-text"><b>{displayName}</b><small>{`${user?.role?.toUpperCase()||'USER'} · @${user?.username||''}`}</small></div><button className="icon-button" title="Sign out" onClick={logout}><LogOut size={16}/></button></div></div></aside>
 <main className="main"><header className="topbar"><button className="icon-button mobile-menu" onClick={()=>setMobile(true)}><Menu/></button><div className="crumb">SLK RAVE <span>/</span> <b>{page}</b></div><div className="top-actions"><span className="date-label">{new Date().toLocaleDateString('en-GB',{weekday:'short',day:'2-digit',month:'short',year:'numeric'}).toUpperCase()}</span><button className="icon-button" onClick={()=>ping('You’re all caught up.')}><Bell size={18}/><i className="notify-dot"/></button><div className="top-divider"/><div className="avatar tiny">{displayName.slice(0,1).toUpperCase()}</div><ChevronDown size={14}/></div></header>
 <div className="page-wrap">{user?.role==='guest'&&<div className="guest-readonly-banner"><ShieldCheck size={16}/><span><b>Guest account — read only</b><small>{auth?.currentUser&&!auth.currentUser.emailVerified?'Verify your email, then sign in again to load financial information.':'Financial information is available in view-only mode.'}</small>{auth?.currentUser&&!auth.currentUser.emailVerified&&<button type="button" className="auth-link" disabled={busy} onClick={resendVerification}>Resend verification email</button>}</span></div>}{canClaimMasterAdmin(user,auth?.currentUser?.email)&&<div className="guest-readonly-banner master-claim-banner"><ShieldCheck size={16}/><span><b>Master Admin setup recovery</b><small>Verify your email, then activate Master Admin access.</small><button type="button" className="auth-link" disabled={busy} onClick={claimMaster}>{busy?'Activating…':'I verified — activate Master Admin'}</button></span></div>}<div className="page-heading"><div><div className="eyebrow"><span className="pulse"/> EVENT FINANCIALS <span className="eyebrow-sep">/</span> SLK26</div><h1>{page==='Overview'?`${timeGreeting()}, ${displayName.split(' ')[0]}`:page}</h1><p>{page==='Overview'?'Here’s what’s happening across your event finances.':page==='Tickets'?'Ticket sales, capacity and tier performance.':page==='Budget'?'Monitor allocations and control event spending.':`Manage and review your event ${page.toLowerCase()}.`}</p></div><div className="heading-actions" /></div>
 {page==='Overview'&&(financeReader?<OverviewDashboard metrics={dashboardSummary} revenues={revenues} expenses={expenses} ticketSales={ticketSales} allocations={allocations}  />:<div className="panel"><div className="panel-head"><div><h3>Ticket overview</h3><p>{sold.toLocaleString()} of {tiers.reduce((n,t)=>n+t.capacity,0).toLocaleString()} tickets sold. Open Tickets for tier availability and permitted actions.</p></div><button className="btn primary" onClick={()=>setPage('Tickets')}>View tickets</button></div></div>)}
 {page==='Tickets'&&<Tickets tiers={tiers} ticketSales={ticketSales} setModal={setModal} role={role} admin={admin} actor={displayName} actorId={displayUid} ping={ping}/>}
 {page==='Revenues'&&<Ledger title="Revenue ledger" rows={filteredRev} search={queryText} setSearch={setQueryText} add={()=>setModal('revenue')} canAdd={role==='admin'||role==='executive'} admin={admin} readOnly={!canManageFinancialRecords(role)} showAgent onEdit={(x:any)=>editFinancialRecord('revenue',x)} onDelete={(x:any)=>deleteFinancialRecord('revenue',x)} />}
 {page==='Expenses'&&<Ledger title="Expense ledger" rows={filteredExp} search={queryText} setSearch={setQueryText} add={()=>setModal('expense')} canAdd={role==='admin'||role==='executive'} admin={admin} readOnly={!canManageFinancialRecords(role)} showAgent onEdit={(x:any)=>editFinancialRecord('expense',x)} onDelete={(x:any)=>deleteFinancialRecord('expense',x)} />}
 {page==='Budget'&&<Budget allocations={allocations} expenses={expenses} total={budget} budgetName={budgetInfo?.name||''} budgetExists={Boolean(budgetInfo)} paid={paidExpense} admin={admin} actor={displayName} actorId={displayUid} ping={ping} />}
 {page==='Categories'&&<CategoriesManager revenues={revenues} expenses={expenses} db={db} actor={displayName} actorId={displayUid} ping={ping}/>}
 {page==='Reports'&&<ReportsPage report={reportView} startDate={reportStart} endDate={reportEnd} setStartDate={setReportStart} setEndDate={setReportEnd} onExport={exportCsv}/>}
 {page==='User management'&&admin&&<UsersPage db={db} self={user?.uid||''} approve={approval} ping={ping}/>}
 {page==='Activity log'&&admin&&<ActivityPage logs={logs} db={db} cursor={logsCursor.current} ping={ping}/>}
 <AppFooter /></div></main>
 {modal&&<RecordModal kind={modal} busy={busy} initial={editRecord} tiers={tiers} revenueCategories={revenueCategories} expenseCategories={budgetExpenseCategories} onClose={()=>{setModal('');setEditRecord(null)}} onSubmit={submitRecord} />}{toast&&<div className="toast"><span/> {toast}</div>}</div>
}
 function AuthScreen({mode,setMode,login,signup,busy,configured,localDev,useEmulators,reset,toast}:any){const [email,setEmail]=useState("");return <div className="auth-shell"><div className="auth-visual"><div className="brand"><BrandLogo /><div><b>SLK RAVE</b><small>FINANCE CENTER</small></div></div><div className="auth-art"><div className="orbit orbit1"/><div className="orbit orbit2"/><div className="orbit orbit3"/><div className="auth-core"><span>SLK</span><b>26</b></div><div className="art-label label1">LIVE EVENT<br/><b>FINANCE</b></div><div className="art-label label2">ONE SYSTEM<br/><b>FULL CONTROL</b></div></div><div className="auth-bottom"><PoweredBy /></div></div><div className={`auth-form-side ${mode==='signup'?'signup-form-side':''}`}><div className={`auth-form-wrap ${mode==='signup'?'signup-form-wrap':''}`}><div className="auth-form-content">{toast&&<div className="toast auth-toast" role="alert"><span/> {toast}</div>}<div className="eyebrow"><span className="pulse"/> SECURE EVENT WORKSPACE</div><h1>{mode==='login'?'Welcome back.':'Join the team.'}</h1><p>{mode==='login'?'Sign in to SLK RAVE Finance Center.':'Create an account to access the workspace.'}</p>{!configured&&<div className="config-alert"><ShieldCheck size={18}/><span><b>{localDev&&!useEmulators?'Local preview is disconnected':'Firebase setup required'}</b><br/>{localDev&&!useEmulators?'Local sign-in and data are disabled. Start the Firebase Auth and Firestore emulators, then set VITE_USE_EMULATORS=true in .env.':'Add your project credentials in .env to enable accounts and live data.'}</span></div>}<form onSubmit={mode==='login'?login:signup} className="auth-form">{mode==='signup'&&<><label>Full name<input name="fullName" placeholder="e.g. Amina Bello" required/></label><label>Username<input name="username" placeholder="amina_bello" required/></label></>}<label>Email address<input name="email" type="email" placeholder="you@mail.com" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input name="password" type="password" placeholder="Enter your password" minLength={8} required/></label>{mode==='signup'&&<label>Confirm password<input name="confirm" type="password" placeholder="Repeat your password" minLength={8} required/></label>}{mode==='login'&&<div className="forgot">Forgot password? <button type="button" className="auth-link" onClick={()=>reset(email)}>Reset it</button></div>}<button disabled={busy||!configured} className="btn primary auth-submit">{busy?'Please wait…':mode==='login'?'Sign in':'Create account'}</button></form><div className="auth-switch">{mode==='login'?<>Don't have an account? <button type="button" className="auth-link" onClick={()=>setMode('signup')}>Sign up</button></>:<>Already have access? <button type="button" className="auth-link" onClick={()=>setMode('login')}>Sign in</button></>}</div></div><AppFooter /></div></div></div>}
function Card({label,value,change,icon,accent,sub}:any){return <div className="kpi card"><div className="kpi-top"><span>{label}</span><div className={`kpi-icon ${accent}`}>{icon}</div></div><div className="kpi-value">{value}</div><div className="kpi-foot">{change&&<span className="positive">↗ {change}</span>}<span>{sub}</span></div></div>}
function chartOptions(){return {responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{backgroundColor:'#14161f',titleColor:'#fff',bodyColor:'#a4a7b7',borderColor:'#2c3040',borderWidth:1}},scales:{x:{grid:{display:false},ticks:{color:'#85899c'}},y:{grid:{color:'#20232e'},ticks:{color:'#85899c'}}}} as any}
function Tickets({tiers,ticketSales,setModal,role,admin,actor,actorId,ping}:any){
  const [editing,setEditing]=useState(false),financeReader=role==='admin'||role==='executive'||role==='member'||role==='guest';
  const canRecord=role==='admin'||role==='executive'||role==='member';
  return <>
    <div className="kpi-grid three">
      <Card label="TICKETS SOLD" value={tiers.reduce((a:number,t:any)=>a+t.sold,0).toLocaleString()} sub="across all tiers" icon={<Ticket size={17}/>} accent="cyan"/>
      {financeReader&&<Card label="TICKET REVENUE" value={formatNaira(ticketSales.reduce((n:number,x:any)=>n+x.total,0))} sub="historical paid ticket sales" icon={<CircleDollarSign size={17}/>} accent="lime"/>}
      <Card label="AVAILABLE CAPACITY" value={tiers.reduce((a:number,t:any)=>a+t.capacity-t.sold,0).toLocaleString()} sub="tickets remaining" icon={<Activity size={17}/>} accent="purple"/>
    </div>
    <div className="panel table-panel"><div className="panel-head"><div><h3>Ticket tiers</h3><p>Capacity and sales by tier</p></div>{admin&&<button className="btn secondary" onClick={()=>setEditing(true)}>Edit tiers</button>}{canRecord&&<button className="btn primary" onClick={()=>setModal('ticket')}><Plus size={15}/> Record Sale</button>}</div>
      <div className="table-scroll"><table><thead><tr><th>TIER</th><th>UNIT PRICE</th><th>SOLD</th><th>CAPACITY</th><th>REMAINING</th>{financeReader&&<th>REVENUE</th>}<th>SALES PROGRESS</th></tr></thead><tbody>{tiers.map((t:any,i:number)=><tr key={t.id}><td><div className="cell-primary"><i className="tier-dot" style={{background:palette[i]}}/>{t.name}</div></td><td>{formatNaira(t.price)}</td><td>{t.sold.toLocaleString()}</td><td>{t.capacity.toLocaleString()}</td><td><span className="pill">{Math.max(0,t.capacity-t.sold).toLocaleString()}</span></td>{financeReader&&<td className="amount-cell">{formatNaira(ticketSales.filter((sale:any)=>sale.tierId===t.id).reduce((n:number,sale:any)=>n+sale.total,0))}</td>}<td><div className="mini-progress"><div className="progress-track"><i style={{width:`${Math.min(100,t.sold/t.capacity*100)}%`,background:palette[i]}}/></div><span>{Math.round(t.sold/t.capacity*100)}%</span></div></td></tr>)}</tbody></table></div>
    </div>
    {financeReader&&<div className="panel table-panel"><div className="panel-head"><div><h3>Ticket sales</h3><p>{ticketSales.length} records · full sales list</p></div></div><div className="table-scroll"><table><thead><tr><th>TIER</th><th>QUANTITY</th><th>UNIT PRICE</th><th>TOTAL</th><th>STATUS</th><th>DATE</th><th>RECORDED BY</th></tr></thead><tbody>{ticketSales.length?ticketSales.map((sale:any)=><tr key={sale.id}><td>{sale.tierName}</td><td>{sale.quantity}</td><td>{formatNaira(sale.unitPrice)}</td><td className="amount-cell">{formatNaira(sale.total)}</td><td><span className={`status ${String(sale.status).toLowerCase()}`}><i/>{sale.status}</span></td><td>{sale.date}</td><td>{sale.agent||''}</td></tr>):<tr><td colSpan={7} className="empty">No ticket sales have been recorded.</td></tr>}</tbody></table></div></div>}
    <div className="panel"><div className="panel-head"><div><h3>Sales by tier</h3><p>Quantity sold versus remaining capacity</p></div></div><div className="chart-mid"><Bar data={{labels:tiers.map((t:any)=>t.name),datasets:[{label:'Sold',data:tiers.map((t:any)=>t.sold),backgroundColor:'#00F5FF',borderRadius:5},{label:'Remaining',data:tiers.map((t:any)=>t.capacity-t.sold),backgroundColor:'#282b37',borderRadius:5}]}} options={chartOptions()}/></div></div>
    {editing&&<TicketTierEditor tiers={tiers} actor={actor} actorId={actorId} onClose={()=>setEditing(false)} ping={ping}/>}
  </>;
}
function Ledger({title,rows,search,setSearch,add,canAdd,admin,onEdit,onDelete,readOnly=false,showAgent=true}:any){
  const emptyColumns=5+(showAgent?1:0)+(readOnly?0:1);
  return <div className="panel table-panel"><div className="panel-head"><div><h3>{title}</h3><p>{rows.length} records</p></div><div className="table-actions"><div className="search"><Search size={15}/><input placeholder="Search records…" value={search} onChange={e=>setSearch(e.target.value)}/></div>{canAdd&&<button className="btn primary" onClick={add}><Plus size={15}/> {title==='Revenue ledger'?'Record Revenue':'Add record'}</button>}</div></div>
    <div className="table-scroll">
      <table>
        <thead><tr><th>DESCRIPTION</th><th>CATEGORY</th><th>AMOUNT</th><th>STATUS</th><th>DATE</th>{showAgent&&<th>RECORDED BY</th>}{!readOnly&&<th>ACTIONS</th>}</tr></thead>
        <tbody>
          {rows.length ? rows.map((x:any) => (
            <tr key={x.id}>
              <td><div className="cell-primary">{x.title}</div></td>
              <td>{x.category}</td>
              <td className="amount-cell">
                <div>{formatNaira(x.amount)}</div>
                {typeof x.previousAmount === 'number' && <small className="previous-amount"><s>{formatNaira(x.previousAmount)}</s></small>}
              </td>
              <td><span className={`status ${x.status.toLowerCase()}`}><i/>{x.status}</span></td>
              <td>{x.date}</td>
              {showAgent && <td>{title==='Expense ledger'?x.agent:<div className="agent-cell"><div className="avatar mini">{x.agent?.slice(0,1)}</div>{x.agent}</div>}</td>}
              {!readOnly && <td><div className="row-actions"><button className="text-action" onClick={() => onEdit(x)}>Edit</button>{admin && <button className="text-action danger" onClick={() => onDelete(x)}>Delete</button>}</div></td>}
            </tr>
          )) : <tr><td colSpan={emptyColumns} className="empty">No records match your search.</td></tr>}
        </tbody>
      </table>
    </div>
    <div className="table-foot">Showing <b>{rows.length}</b> records <span>{readOnly?'Read-only view · no actions available.':'Changes are recorded in the audit log.'}</span></div></div>
}
function Budget({allocations,expenses,total,budgetName,budgetExists,paid,admin,actor,actorId,ping}:any){
 const [editing,setEditing]=useState<null|'edit'|'add'>(null),expenseTotals=summarizeExpenses(expenses),committed=expenseTotals.committed,available=total-paid-committed,pct=total?paid/total*100:0;
 const open=(mode:'edit'|'add')=>setEditing(mode);
 return <>
  {!budgetExists&&admin&&<div className="panel"><div className="panel-head"><div><h3>No event budget yet</h3><p>Create the total budget first, then add spending categories and their allocation percentages.</p></div><button className="btn primary" onClick={()=>open('edit')}><Plus size={15}/>Create budget</button></div></div>}
  <div className="kpi-grid four"><Card label="TOTAL BUDGET" value={formatNaira(total)} sub={budgetExists?`${allocations.length} category allocations`:'Not created'} icon={<Wallet size={17}/>} accent="cyan"/><Card label="PAID SPENDING" value={formatNaira(paid)} sub="cash already spent" icon={<ArrowDownRight size={17}/>} accent="pink"/><Card label="COMMITMENTS" value={formatNaira(committed)} sub="pending and unpaid expenses" icon={<CircleDollarSign size={17}/>} accent="purple"/><Card label="AVAILABLE AFTER COMMITMENTS" value={formatNaira(available)} sub="budget less paid and committed" icon={<BarChart3 size={17}/>} accent="lime"/></div>
  {budgetExists&&<>
   <div className="budget-hero panel"><div><div className="eyebrow">{budgetName||'EVENT BUDGET'}</div><h2>{formatNaira(paid)} <small>/ {formatNaira(total)}</small></h2><p>{pct.toFixed(1)}% utilized <span>·</span> {formatNaira(total-paid)} cash remaining <span>·</span> {formatNaira(available)} after commitments</p></div><div className="hero-gauge"><div className="gauge-ring" style={{background:`conic-gradient(#00F5FF ${Math.min(pct,100)*3.6}deg,#242833 0)`}}><div><b>{Math.round(pct)}%</b><small>UTILIZED</small></div></div></div></div>
   <div className="grid-main budget-grid"><div className="panel"><div className="panel-head"><div><h3>Allocation utilization</h3><p>Allocated, paid, committed and available after commitments by category</p></div></div>{allocations.length?<div className="chart-mid"><Bar data={{labels:allocations.map((a:any)=>a.category),datasets:[{label:'Allocated',data:allocations.map((a:any)=>a.amount),backgroundColor:'#292d3a',borderRadius:4},{label:'Paid',data:allocations.map((a:any)=>summarizeAllocationExpenses(expenses,a).paid),backgroundColor:'#00F5FF',borderRadius:4},{label:'Committed',data:allocations.map((a:any)=>summarizeAllocationExpenses(expenses,a).committed),backgroundColor:'#ff2bd6',borderRadius:4},{label:'Available after commitments',data:allocations.map((a:any)=>a.amount-summarizeAllocationExpenses(expenses,a).paid-summarizeAllocationExpenses(expenses,a).committed),backgroundColor:'#B6FF00',borderRadius:4}]}} options={chartOptions()}/></div>:<div className="empty">Add a category allocation to start tracking your budget.</div>}</div>
   <div className="panel allocation-panel"><div className="panel-head"><div><h3>Budget allocation</h3><p>Share of approved event budget</p></div></div>{allocations.length?<><div className="distribution"><div className="distribution-chart"><Doughnut data={{labels:allocations.map((a:any)=>a.category),datasets:[{data:allocations.map((a:any)=>a.amount),backgroundColor:palette,borderWidth:0}]}} options={{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}}}}/></div></div><div className="allocation-legend">{allocations.map((a:any,i:number)=><div key={a.id}><span><i style={{background:palette[i%palette.length]}}/>{a.category}</span><b>{Number(a.percent??(total?a.amount/total*100:0)).toFixed(2)}%</b></div>)}</div></>:<div className="empty">No allocations added yet.</div>}</div></div>
   <div className="panel"><div className="panel-head"><div><h3>Category breakdown</h3><p>Paid spending, commitments and available funds by allocation</p></div>{admin&&<div className="table-actions"><button className="btn secondary" onClick={()=>open('edit')}>Edit budget</button><button className="btn primary" onClick={()=>open('add')}><Plus size={15}/>Add allocation</button></div>}</div><div className="table-scroll"><table><thead><tr><th>CATEGORY</th><th>ALLOCATION</th><th>ALLOCATED</th><th>PAID</th><th>COMMITTED</th><th>CASH REMAINING</th><th>AFTER COMMITMENTS</th><th>UTILIZATION</th></tr></thead><tbody>{allocations.map((a:any)=>{const categoryTotals=summarizeAllocationExpenses(expenses,a),spent=categoryTotals.paid,categoryCommitted=categoryTotals.committed,u=a.amount?spent/a.amount*100:0;return <tr key={a.id}><td className="cell-primary">{a.category}</td><td>{Number(a.percent??(total?a.amount/total*100:0)).toFixed(2)}%</td><td>{formatNaira(a.amount)}</td><td className="amount-cell">{formatNaira(spent)}</td><td>{formatNaira(categoryCommitted)}</td><td>{formatNaira(a.amount-spent)}</td><td>{formatNaira(a.amount-spent-categoryCommitted)}</td><td><div className="mini-progress"><div className="progress-track"><i style={{width:`${Math.min(100,u)}%`}}/></div><span>{Math.round(u)}%</span></div></td></tr>})}</tbody></table></div></div>
  </>}
  {editing&&<BudgetEditor key={editing} allocations={allocations} total={total} budgetName={budgetName} budgetExists={budgetExists} initialAdd={editing==='add'} actor={actor} actorId={actorId} onClose={()=>setEditing(null)} ping={ping}/>}
 </>;
}
function UsersPage({db,self,approve,ping}:any){
 const [rows,setRows]=useState<any[]>([]),[loaded,setLoaded]=useState(false),[pendingRoles,setPendingRoles]=useState<Record<string,Role>>({});
 const requestReason=(action:string)=>{const value=window.prompt('Enter a reason to '+action+' (required, up to 500 characters):');if(value===null)return null;const reason=value.trim();if(!reason||reason.length>500){ping('Enter a reason of 1–500 characters for this access change.');return null}return reason};
 const formatDate=(v:any)=>{if(!v)return '—';const d=typeof v?.toDate==='function'?v.toDate():(typeof v?.seconds==='number'?new Date(v.seconds*1000):new Date(v));return isNaN(d.getTime())?'—':d.toLocaleDateString('en-GB')};
 useEffect(()=>{if(!db)return;return onSnapshot(collection(db,'usersPublic'),s=>{setRows(s.docs.map(d=>d.data()).filter(u=>u.uid!==self));setLoaded(true)},e=>notifyError('load team accounts',e,ping,'Team accounts could not be loaded. Check your connection and permissions.'))},[db,self]);
 const otherApprovedAdmins=rows.filter(u=>u.status==='approved'&&u.role==='admin');
 const roleOptions=<><option value="admin">Admin</option><option value="executive">Executive Agent</option><option value="member">Member Agent</option><option value="guest">Guest</option></>;
 return <div className="panel table-panel"><div className="panel-head"><div><h3>Team access</h3><p>Review account requests and manage access</p></div><span className="counter">{rows.filter(u=>u.status==='pending').length} PENDING</span></div>
 {loaded&&otherApprovedAdmins.length===0&&<div className="callout"><ShieldCheck size={17}/><span><b>Set up backup Admin access.</b> No other approved Admin profile is listed. Approve a separate account as Admin, then confirm its owner verifies their email and can sign in.</span></div>}
 <div className="table-scroll"><table><thead><tr><th>NAME</th><th>USERNAME</th><th>EMAIL</th><th>ROLE</th><th>STATUS</th><th>REGISTERED</th><th>ACTIONS</th></tr></thead><tbody>{rows.map(u=>{
  const protectedAccount=u.isMasterAdmin===true||String(u.email||'').toLowerCase()===MASTER_EMAIL;
  const chosenRole=pendingRoles[u.uid]??'member';
  return <tr key={u.uid}><td className="cell-primary">{u.fullName}</td><td>@{u.username}</td><td>{u.email}</td>
   <td>{u.status==='pending'?<select className="inline-select" value={chosenRole} onChange={e=>setPendingRoles(previous=>({...previous,[u.uid]:e.target.value as Role}))} aria-label={`Role for ${u.fullName}`} disabled={protectedAccount}>{roleOptions}</select>:u.status==='approved'?<select className="inline-select" value={u.role||'member'} onChange={e=>{const role=e.target.value as Role;if(role!==u.role){const reason=requestReason('change this user role');if(reason)approve(u.uid,'role',role,reason)}}} aria-label={`Role for ${u.fullName}`} disabled={protectedAccount}>{roleOptions}</select>:<span>{u.role||'Unassigned'}</span>}</td>
   <td><span className={`status ${u.status==='approved'?'paid':'pending'}`}><i/>{u.status}</span></td><td>{formatDate(u.createdAt)}</td>
   <td>{protectedAccount?<span className="muted">Protected Master Admin</span>:u.status==='pending'?<div className="row-actions"><button className="text-action" onClick={()=>{const reason=requestReason('approve this account and assign its role');if(reason)approve(u.uid,'approve',chosenRole,reason)}}>Approve</button><button className="text-action danger" onClick={()=>approve(u.uid,'reject','member')}>Reject</button></div>:u.status==='approved'?<button className="text-action danger" onClick={()=>{if(window.confirm(`Suspend access for ${u.fullName}?`))(()=>{const reason=requestReason('suspend this account');if(reason)approve(u.uid,'suspend',u.role,reason)})()}}>Suspend</button>:<button className="text-action" onClick={()=>{const reason=requestReason('reactivate this account');if(reason)approve(u.uid,'reactivate',u.role,reason)}}>Reactivate</button>}</td>
  </tr>})}</tbody></table></div>{rows.length===0&&<div className="empty">No other team members yet.</div>}</div>
}
function RecordModal({kind,busy,initial,tiers,revenueCategories,expenseCategories,onClose,onSubmit}:any){
  const availableTiers=tiers.filter((t:any)=>t.active===true&&t.sold<t.capacity);
  const [selectedTierId,setSelectedTierId]=useState(availableTiers[0]?.id||'');
  const [quotedUnitPrice,setQuotedUnitPrice]=useState(Number(availableTiers[0]?.price)||0);
  const categoryOptions=kind==='expense'?expenseCategories:revenueCategories;
  const categories=initial?.category&&!categoryOptions.includes(initial.category)?[initial.category,...categoryOptions]:categoryOptions;
  return <div className="modal-overlay" onClick={onClose}><div className="modal" onClick={e=>e.stopPropagation()}>
    <div className="modal-head"><div><div className="eyebrow">{initial?'EDIT RECORD':'NEW RECORD'}</div><h2>{kind==='ticket'?'Record ticket sale':initial?'Edit '+kind:kind==='expense'?'Add an expense':'Add revenue'}</h2></div><button className="icon-button" onClick={onClose}><X/></button></div>
    <form onSubmit={onSubmit}><div className="modal-body">{kind==='ticket'?<>
      <label>Ticket tier<select name="tier" value={selectedTierId} onChange={e=>{const next=tiers.find((t:any)=>t.id===e.target.value);setSelectedTierId(e.target.value);setQuotedUnitPrice(Number(next?.price)||0)}} required>{tiers.map((t:any)=><option key={t.id} value={t.id} disabled={t.active!==true||t.sold>=t.capacity}>{t.name} · {formatNaira(t.price)} · {Math.max(0,t.capacity-t.sold)} left</option>)}</select></label>
      <input type="hidden" name="quotedUnitPrice" value={quotedUnitPrice}/>
      <p className="field-hint">Quoted price: {formatNaira(quotedUnitPrice)} per ticket. Close and reopen this form to review a changed price.</p>
      <label>Quantity<input name="quantity" type="number" min="1" max="20" step="1" defaultValue="1" required/></label>
      <label>Sale date<input name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></label>
      <div className="callout"><ShieldCheck size={16}/><span>Capacity is validated atomically before the sale is saved.</span></div>
    </>:<>
      <label>Description<input name="title" defaultValue={initial?.title||''} placeholder={kind==='expense'?'e.g. Stage lighting deposit':'e.g. Brand sponsorship'} required/></label>
      <label>Category<select name="category" defaultValue={initial?.category||categories[0]} required>{categories.map((c:string)=><option key={c} value={c}>{c}</option>)}</select></label>
      <label>Amount (₦)<input name="amount" defaultValue={initial?.amount||''} inputMode="numeric" placeholder="0" min="1" step="1" required/>{kind==='expense'&&typeof initial?.amount==='number'&&<small className="previous-amount-note">Previous amount: <s>{formatNaira(initial.amount)}</s></small>}</label>
      <div className="form-two"><label>Payment status<select name="status" defaultValue={initial?.status||'Paid'}>{(kind==='expense'?['Paid','Pending','Deposit']:['Paid','Pending','Unpaid']).map(status=><option key={status}>{status}</option>)}{kind==='expense'&&initial?.status==='Unpaid'&&<option value="Unpaid">Unpaid (legacy)</option>}</select></label>
      <label>Date<input name="date" type="date" defaultValue={initial?.date||new Date().toISOString().slice(0,10)} required/></label></div>
      {kind==='revenue'&&<label>Payment method<select name="method" defaultValue={initial?.method||'Bank transfer'}><option>Bank transfer</option><option>POS</option><option>Cash</option><option>Online</option></select></label>}
      {initial&&<label>Reason for change<textarea name="reason" maxLength={500} placeholder="Required when the amount or payment status changes; optional for other edits."/></label>}
    </>}</div>
    <div className="modal-foot"><button type="button" className="btn secondary" onClick={onClose}>Cancel</button><button disabled={busy} className="btn primary">{busy?'Saving…':<><Plus size={15}/>{initial?'Update record':'Save record'}</>}</button></div></form>
  </div></div>;
}
